name: Performance Regression Check

on:
  pull_request:
    branches: [master]

jobs:
  benchmark:
    name: Time benchmark

    runs-on: ubuntu-latest

    steps:
      # check out pull request branch
      - uses: actions/checkout@v2
          with:
            path: pr
      # check out master branch (to compare performance)
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Run baseline benchmark (master)
        run: npm install && node master/benchmarks/benchmark.js | tee baseline.txt

      - name: Run benchmark
        run: npm install && node pr/benchmarks/benchmark.js | tee pr.txt

      - name: Compare benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          # Where the output from the benchmark tool is stored
          output-file-path: pr.txt
          # Where the baseline data file is stored
          external-data-json-path: baseline.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '30%'
          fail-threshold: '100%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@larabr'