name: Test in browsers

on:
  workflow_run:
    workflows: [Build]
    types: [completed]


jobs:
  test-browsers-latest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Retrieve cached folders
        uses: actions/cache/restore@v3
        id: cache-full
        with:
          path: |
            dist
            test/lib
          key: cache-${{ github.sha }}
        # ignore cache miss, since it was taken care of the `build-tests-full` step and it should never occur here

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install Chrome
        run: npx playwright install-deps chrome

      - name: Install Firefox
        run: npx playwright install-deps firefox

      - name: Install Webkit
        run: npx playwright install-deps webkit

      - name: Run browser tests
        run: npm run test-browser

      - name: Run browser tests (lightweight) # overwrite test/lib
        run: |
          npm run build-test --lightweight
          npm run test-browser

  test-browsers-compatibility:
    runs-on: ubuntu-latest
    needs: test-browsers-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Retrieve cached dist folder
        uses: actions/cache/restore@v3
        id: cache-full
        with:
          path: |
            dist
            test/lib
          key: cache-${{ github.sha }}
        # ignore cache miss, since it was taken care of the `build-tests-full` step and it should never occur here

      - name: Wait for other Browserstack tests to finish
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
          abort-after-seconds: 900
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run browserstack tests
        run: npm run test-browserstack

      - name: Run browserstack tests (lightweight) # overwrite test/lib
        run: |
          npm run build-test --lightweight
          npm run test-browserstack
        env:
          LIGHTWEIGHT: true
