# reusable workflow, see
# https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
name: Build and cache
on: 
  workflow_call:  # allow this workflow to be called from other workflows
    outputs:
      cache-key:
        description: "Cache key"
        value: ${{ jobs.build-tests.outputs.cache-key }}
jobs:
  build-tests: # cache both dist and tests (non-lightweight only), based on commit hash
    runs-on: ubuntu-latest
    outputs:
      cache-key: cache-$GITHUB_SHA
    steps:
      - uses: actions/checkout@v3
      - name: Check for cached folders
        id: cache-full
        uses: actions/cache@v3
        with:
          path: |
            dist
            test
          key: cache-$GITHUB_SHA
      - name: Build dist and tests
        if: steps.cache-full.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: latest
          run: |
            npm ci
            npm run build-test
