name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build: # cache both dist and tests (non-lightweight only), based on commit hash
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check for cached folders
        id: cache-full
        uses: actions/cache@v3
        with:
          path: |
            dist
            test/lib
          key: cache-${{ github.sha }}
      - name: Build dist and tests
        if: steps.cache-full.outputs.cache-hit != 'true'
        run: |
          npm ci
          npm run build-test

  types:
    name: Test type definitions
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci --ignore-scripts # TS
    - name: Retrieve cached folders
      uses: actions/cache/restore@v3
      id: cache-full
      with:
        path: |
          dist
          test/lib
        key: cache-${{ github.sha }}
    - run: npm run test-type-definitions

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci --ignore-scripts # linter
    - name: Retrieve cached folders
      uses: actions/cache/restore@v3
      id: cache-full
      with:
        path: |
          dist
          test/lib
        key: cache-${{ github.sha }}
    - run: npm run lint
