name: Types

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  types:
    name: Test type definitions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Retrieve cached folders
      uses: actions/cache/restore@v3
      id: cache-full
      with:
        path: dist
        key: cache-${{ github.sha }}
        # ignore cache miss, since it was taken care of the `build-tests-full` step and it should never occur here

    - run: npm ci --ignore-scripts
    - run: npm run test-type-definitions
